version = 0.1
print("-----------------------------------------")
print("Meowerity Works alpha " version)
print("By Meowerity")
print("-----------------------------------------")
print("--!--!--!--!--!--!--!--!--!--!--!--!--!-- Meowerity CUI")
print("This Meowerity Works version is a gamemode to be included in addons.")
print("and this is for testing purposes only.")
print("This is not a final version. There will be big updates in the future.")
print("--!--!--!--!--!--!--!--!--!--!--!--!--!--")
